<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Imposter" Version="0.1.4" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
        <PackageReference Include="MSTest.TestAdapter" Version="4.1.0" />
        <PackageReference Include="MSTest.TestFramework" Version="4.1.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CKLunchBot.Core\CKLunchBot.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="TestData\menu.html" />
    </ItemGroup>

</Project>
