name: Tweet lunch menu

on:
  schedule:
    - cron: '50 2 * * MON-FRI'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: api_keys
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Debug # 충분한 테스트 후 Release로 바꾸기
    - name: Run
      run:  dotnet run --project ./src/CKLunchBot.Actions --no-build -- lunch
