name: Tweet breakfast menu

on:
  schedule:
    - cron: '30 22 * * 0-4' # KST 07:30

env:
  MENU_TYPE: breakfast
  
  DLL_NAME: CKLunchBot.Actions.dll
  PUBLISH_PATH: src/CKLunchBot.Actions/published
  CONFIGURATION: Release
  DOTNET_VERSION: 6.0.x
  WORKING_DIRECTORY: src/CKLunchBot.Actions
jobs:
  tweet:
    runs-on: ubuntu-latest
    environment: api_keys
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: Build
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.PUBLISH_PATH }}"

      - name: Run
        env:
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          cd "${{ env.PUBLISH_PATH }}"
          dotnet "${{ env.DLL_NAME }}" ${{ env.MENU_TYPE }}