name: Tweet lunch menu

on:
  schedule:
    - cron: '0 0 * * 1-5' # KST 09:00

env:
  MENU_TYPE: lunch
  PROJECT_PATH: src/CKLunchBot.Actions
  CONFIGURATION: Release
  DOTNET_VERSION: 6.0.x
jobs:
  tweet:
    runs-on: ubuntu-latest
    environment: api_keys
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Run
        env:
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          cd "${{ env.PROJECT_PATH }}"
          dotnet run --configuration ${{ env.CONFIGURATION }} --no-build -- ${{ env.MENU_TYPE }}
