name: Tweet briefing

on:
  schedule:
    - cron: "10 21 * * 0-4" # KST 06:10

env:
  PROJECT_PATH: src/CKLunchBot.Actions
  CONFIGURATION: Release
  DOTNET_VERSION: 7.0.x
jobs:
  tweet:
    runs-on: ubuntu-latest
    environment: api_keys
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Run
        env:
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          cd "${{ env.PROJECT_PATH }}"
          dotnet run --configuration ${{ env.CONFIGURATION }} --no-build -- briefing
