name: Tweet breakfast menu

on:
  schedule:
    - cron: "00 23 * * *" # KST 08:00

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    environment: api_keys
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ./src/CKLunchBot.Actions --no-restore -c Release
      - name: Run
        env:
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_SECRET_KEY }}
        run: dotnet run --project ./src/CKLunchBot.Actions -c Release --no-build -- breakfast
